import type { Metadata } from "next";
import GlobalStyle from "../styles/globalStyle";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Providers from "../until/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <GlobalStyle>
        <html lang="en">
          <body>{children}</body>
        </html>
      </GlobalStyle>
    </Providers>
  );
}
